"""Add seen_cards table for tracking new cards

Revision ID: a6ff9ebdf638
Revises: add_summary_edited_column
Create Date: 2025-08-20 22:15:30.960174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6ff9ebdf638'
down_revision: Union[str, Sequence[str], None] = 'add_summary_edited_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_interactions_card_link'), table_name='user_card_interactions')
    op.drop_index(op.f('ix_user_card_interactions_first_seen_at'), table_name='user_card_interactions')
    op.drop_index(op.f('ix_user_card_interactions_session_id'), table_name='user_card_interactions')
    op.drop_index(op.f('ix_user_card_interactions_viewed_at'), table_name='user_card_interactions')
    op.drop_table('user_card_interactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card_interactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_viewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_card_interactions_pkey'))
    )
    op.create_index(op.f('ix_user_card_interactions_viewed_at'), 'user_card_interactions', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_user_card_interactions_session_id'), 'user_card_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_card_interactions_first_seen_at'), 'user_card_interactions', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_user_card_interactions_card_link'), 'user_card_interactions', ['card_link'], unique=False)
    # ### end Alembic commands ###
