"""add user_id to bookmarks

Revision ID: bef120028def
Revises: c2d7970f40de
Create Date: 2025-08-28 02:13:10.634178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
import hashlib
import os

# revision identifiers, used by Alembic.
revision: str = 'bef120028def'
down_revision: Union[str, Sequence[str], None] = 'c2d7970f40de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _hash_password(password: str) -> str:
    """Hash password using hashlib (simple implementation for now)"""
    salt = os.urandom(32)
    pwdhash = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 100000)
    return salt.hex() + pwdhash.hex()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('user_id', sa.UUID(), nullable=True))

    # Create a default user for existing bookmarks
    users_table = sa.table('users',
        sa.column('id', sa.UUID()),
        sa.column('email', sa.String()),
        sa.column('username', sa.String()),
        sa.column('password_hash', sa.String()),
        sa.column('created_at', sa.DateTime()),
        sa.column('last_login', sa.DateTime()),
        sa.column('is_active', sa.Boolean())
    )
    connection = op.get_bind()
    default_user_email = 'default_user@example.com'
    default_user = connection.execute(sa.select(users_table).where(users_table.c.email == default_user_email)).first()

    if not default_user:
        default_user_id = uuid.uuid4()
        password = os.urandom(16).hex()
        password_hash = _hash_password(password)
        connection.execute(users_table.insert().values(
            id=default_user_id,
            email=default_user_email,
            username='default_user',
            password_hash=password_hash,
            created_at=sa.func.now(),
            is_active=True
        ))
        user_id = default_user_id
    else:
        user_id = default_user.id

    # Update existing bookmarks with the default user's id
    bookmarks_table = sa.table('bookmarks', sa.column('user_id', sa.UUID()))
    op.execute(bookmarks_table.update().values(user_id=user_id))

    # Now, alter the column to be non-nullable
    op.alter_column('bookmarks', 'user_id', nullable=False)

    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_foreign_key('fk_bookmarks_user_id_users', 'bookmarks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookmarks_user_id_users', 'bookmarks', type_='foreignkey')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_column('bookmarks', 'user_id')
    # ### end Alembic commands ###