"""initial schema

Revision ID: ef180e16550e
Revises: 
Create Date: 2026-10-04 02:02:49.639986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef180e16550e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_cache_created_at'), 'embedding_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_embedding_cache_text'), 'embedding_cache', ['text'], unique=False)
    op.create_index(op.f('ix_embedding_cache_text_hash'), 'embedding_cache', ['text_hash'], unique=True)
    op.create_table('seen_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('card_link', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seen_cards_card_link'), 'seen_cards', ['card_link'], unique=False)
    op.create_index(op.f('ix_seen_cards_seen_at'), 'seen_cards', ['seen_at'], unique=False)
    op.create_index(op.f('ix_seen_cards_session_id'), 'seen_cards', ['session_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('source_link', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('summary_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(summary, ''))", ), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_sources_date'), 'sources', ['date'], unique=False)
    op.create_index(op.f('ix_sources_link'), 'sources', ['link'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('custom_topics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('source_tag', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_edited', sa.String(), nullable=True),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_bookmarked_at'), 'bookmarks', ['bookmarked_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_link'), 'bookmarks', ['link'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('comment_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_insights_generated_at'), 'comment_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_comment_insights_link'), 'comment_insights', ['link'], unique=False)
    op.create_index(op.f('ix_comment_insights_source_id'), 'comment_insights', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_insights_source_id'), table_name='comment_insights')
    op.drop_index(op.f('ix_comment_insights_link'), table_name='comment_insights')
    op.drop_index(op.f('ix_comment_insights_generated_at'), table_name='comment_insights')
    op.drop_table('comment_insights')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_link'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_bookmarked_at'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_link'), table_name='sources')
    op.drop_index(op.f('ix_sources_date'), table_name='sources')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_seen_cards_session_id'), table_name='seen_cards')
    op.drop_index(op.f('ix_seen_cards_seen_at'), table_name='seen_cards')
    op.drop_index(op.f('ix_seen_cards_card_link'), table_name='seen_cards')
    op.drop_table('seen_cards')
    op.drop_index(op.f('ix_embedding_cache_text_hash'), table_name='embedding_cache')
    op.drop_index(op.f('ix_embedding_cache_text'), table_name='embedding_cache')
    op.drop_index(op.f('ix_embedding_cache_created_at'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
